// Script to generate the complete products.js file
const fs = require('fs');

const products = [
    // ─── INVITADA TALLA GRANDE ───
    { id: 1, name: 'VESTIDO LENTEJUELA ANA', price: 119.99, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande', 'Destacado'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/IMG_6737.jpeg', description: 'Vestido adornado con lentejuelas, perfecto para bodas y celebraciones.', sizes: ['XL', 'XXL', '3XL'] },
    { id: 2, name: 'VESTIDO LUISA', price: 129.99, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/8975-1.jpg', description: 'Vestido elegante con corte favorecedor. Para todas las siluetas.', sizes: ['XL', 'XXL', '3XL', '4XL'] },
    { id: 3, name: 'VESTIDO NUDE', price: 149.99, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande', 'Fiesta'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/09/IMG_7165.jpg', description: 'Vestido en tono nude con detalles sofisticados. Perfecto para eventos formales.', sizes: ['XL', 'XXL', '3XL'] },
    { id: 4, name: 'VESTIDO CURVI ANA', price: 59.99, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/09/18026.jpg', description: 'Vestido curvy con corte moderno y favorecedor. Elegancia sin límites.', sizes: ['XL', 'XXL', '3XL', '4XL'] },
    { id: 5, name: 'VESTIDO CURVI SONIA', price: 89.99, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/09/25259-1.jpg', description: 'Vestido curvy elegante con diseño favorecedor. Estilo sin límites de talla.', sizes: ['XL', 'XXL', '3XL', '4XL'] },
    { id: 6, name: 'VESTIDO CURVI MARIA', price: 135.00, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/09/7930.jpg', description: 'Vestido curvy con acabado premium. Diseñado para realzar tu belleza.', sizes: ['XL', 'XXL', '3XL', '4XL'] },
    { id: 7, name: 'VESTIDO CURVI LUCIA', price: 75.99, originalPrice: null, category: 'Invitada Talla Grande', subcategory: null, tags: ['Invitada Talla Grande'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/09/jr2252.jpg', description: 'Vestido curvy con estilo moderno y sofisticado. Comodidad y elegancia.', sizes: ['XL', 'XXL', '3XL', '4XL'] },
    { id: 8, name: 'VESTIDO TORONTO', price: 230.00, originalPrice: null, category: 'Fiesta', subcategory: 'fiesta-vestidos-largos', tags: ['Invitada Talla Grande', 'Fiesta'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/04/IMG_3558.jpg', description: 'Vestido largo de alta costura. Pieza excepcional para grandes eventos.', sizes: ['S', 'M', 'L', 'XL', 'XXL'] },
    { id: 9, name: 'VESTIDO VALENTINA', price: 189.00, originalPrice: null, category: 'Fiesta', subcategory: 'fiesta-vestidos-largos', tags: ['Invitada Talla Grande', 'Fiesta'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/04/IMG_2681.jpg', description: 'Vestido largo con diseño exclusivo. Elegancia atemporal para cada ocasión.', sizes: ['S', 'M', 'L', 'XL', 'XXL'] },

    // ─── COMPLEMENTOS ───
    { id: 10, name: 'BOLSO NEGRO ASA DE MADERA', price: 22.99, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/IMG_6668.jpeg', description: 'Bolso negro con asa de madera. Elegante y práctico para uso diario.', sizes: [] },
    { id: 11, name: 'BOLSO CADERA COLORES', price: 19.99, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/IMG_6668.jpeg', description: 'Bolso de cadera multicolor. Práctico y lleno de estilo.', sizes: [] },
    { id: 12, name: 'BOLSO ESPAÑA', price: 24.99, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/IMG_6668.jpeg', description: 'Bolso con diseño inspirado en España. Artesanía y estilo únicos.', sizes: [] },
    { id: 13, name: 'BOLSO PISA', price: 39.99, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_2544.jpg', description: 'Bolso elegante con acabado premium. Perfecto para cualquier ocasión.', sizes: [] },
    { id: 14, name: 'BOLSO MYKONOS', price: 24.00, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Nueva Colección', 'Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/02/IMG_1528.jpeg', description: 'Bolso de mano en tonos mediterráneos. Compacto y versátil.', sizes: [] },
    { id: 15, name: 'BOLSO ORLEANS', price: 24.99, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Nueva Colección', 'Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/02/IMG_1526.jpeg', description: 'Bolso estilo clásico con acabado premium. El complemento ideal.', sizes: [] },
    { id: 16, name: 'BOLSO BOHO', price: 28.00, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Nueva Colección', 'Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/02/IMG_1507.jpeg', description: 'Bolso estilo boho con detalles artesanales. Para tus looks más libres.', sizes: [] },
    { id: 17, name: 'PENDIENTES NURIA', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/IMG_6322.jpeg', description: 'Pendientes colgantes con detalle de cristal. El toque perfecto.', sizes: [] },
    { id: 18, name: 'PENDIENTES NADIA', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/01/IMG_6323.jpeg', description: 'Pendientes elegantes con diseño moderno. Complemento imprescindible.', sizes: [] },
    { id: 19, name: 'PENDIENTE SOL', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/04/IMG_2566.jpg', description: 'Pendientes con forma de sol. Luminosos y perfectos para el verano.', sizes: [] },
    { id: 20, name: 'PENDIENTES FLORENCIA', price: 6.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_2086.jpg', description: 'Pendientes con inspiración florentina. Sofisticación italiana.', sizes: [] },
    { id: 21, name: 'PENDIENTES GUEPARDO', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_8428.jpg', description: 'Pendientes con estampado de guepardo. Estilo animal print atrevido.', sizes: [] },
    { id: 22, name: 'PENDIENTES ZEBRA', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_8432.jpg', description: 'Pendientes con estampado de cebra. Look salvaje y sofisticado.', sizes: [] },
    { id: 23, name: 'PENDIENTES MARIPOSA', price: 10.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/1-21.jpg', description: 'Pendientes con forma de mariposa. Delicados y llenos de encanto.', sizes: [] },
    { id: 24, name: 'PENDIENTES HOJA', price: 10.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/2-18.jpg', description: 'Pendientes con diseño de hoja natural. Inspiración botánica.', sizes: [] },
    { id: 25, name: 'ARGOLLAS BEA', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-pendientes', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/1.jpg', description: 'Argollas clásicas con acabado brillante. Un básico imprescindible.', sizes: [] },
    { id: 26, name: 'COLLAR ESTRELLA', price: 20.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/09/IMG_6637.jpg', description: 'Collar con colgante de estrella. Elegancia celestial para cualquier outfit.', sizes: [] },
    { id: 27, name: 'COLLAR FLOR', price: 12.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/08/IMG_5116.jpg', description: 'Collar con colgante de flor. Delicado y femenino.', sizes: [] },
    { id: 28, name: 'COLLAR PAQUI', price: 11.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/05/IMG_8180.jpg', description: 'Collar con diseño artesanal. Pieza única y especial.', sizes: [] },
    { id: 29, name: 'COLLAR PRAGA', price: 9.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_9361.jpg', description: 'Collar inspirado en la ciudad de Praga. Elegancia centroeuropea.', sizes: [] },
    { id: 30, name: 'COLLAR CORAZON', price: 11.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_8450-1.jpg', description: 'Collar con colgante de corazón. El regalo perfecto.', sizes: [] },
    { id: 31, name: 'COLLAR MODELO CORBATA', price: 10.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_8463.jpg', description: 'Collar tipo corbata con diseño vanguardista. Pieza statement.', sizes: [] },
    { id: 32, name: 'COLLAR AFRICANO', price: 12.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_8470.jpg', description: 'Collar con inspiración africana. Colores vibrantes y diseño étnico.', sizes: [] },
    { id: 33, name: 'COLLAR MULTI', price: 8.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/02/image00003.jpeg', description: 'Collar multicapa con varias cadenas. Tendencia y versatilidad.', sizes: [] },
    { id: 34, name: 'COLLAR MONEDA', price: 6.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/02/image00001.jpeg', description: 'Collar con colgante de moneda. Estilo bohemio y chic.', sizes: [] },
    { id: 35, name: 'COLLAR INSPIRACIÓN OSO', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/02/image00002.jpeg', description: 'Collar con colgante de osito. Divertido y con carácter.', sizes: [] },
    { id: 36, name: 'COLLAR PERRITO', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/3-5.jpg', description: 'Collar con colgante de perrito. Para las amantes de los animales.', sizes: [] },
    { id: 37, name: 'COLLAR NÁCAR', price: 6.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/1-7.jpg', description: 'Collar con detalles de nácar. Brillo natural y sofisticado.', sizes: [] },
    { id: 38, name: 'COLLAR BABERO', price: 19.00, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/04/IMG_2746.jpg', description: 'Collar tipo babero con diseño statement. Pieza que transforma cualquier look.', sizes: [] },
    { id: 39, name: 'COLLAR BOLAS', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Nueva Colección', 'Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/02/IMG_0593-1.jpeg', description: 'Collar de bolas con acabado brillante. Tendencia pura.', sizes: [] },
    { id: 40, name: 'ROSARIO MEDIANO BOLA', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/2-25.jpg', description: 'Rosario mediano con cuentas de bola. Accesorio versátil y con estilo.', sizes: [] },
    { id: 41, name: 'ROSARIO MEDIANO', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-collares', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2024/07/1-24.jpg', description: 'Rosario mediano clásico. Accesorio atemporal con toque espiritual.', sizes: [] },
    { id: 42, name: 'ANILLO FANTASI', price: 6.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-anillos', tags: ['Nueva Colección', 'Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/02/IMG_1167.jpeg', description: 'Anillo de fantasía con piedra semipreciosa. Un punto de luz para tu mano.', sizes: [] },
    { id: 43, name: 'CINTURÓN TURQUÍA', price: 7.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-cinturones', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_1068.jpg', description: 'Cinturón con diseño turco artesanal. Detalle étnico único.', sizes: [] },
    { id: 44, name: 'CINTURÓN ESTRECHO', price: 11.99, originalPrice: null, category: 'Complementos', subcategory: 'complementos-cinturones', tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2026/02/IMG_0593.jpeg', description: 'Cinturón estrecho con hebilla dorada. El detalle que marca la diferencia.', sizes: [] },
    { id: 45, name: 'CUELLO DE PELO', price: 12.99, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Complementos'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/12/IMG_5388.jpeg', description: 'Cuello de pelo suave y cálido. Accesorio perfecto para el invierno.', sizes: [] },
    { id: 46, name: 'MEDIA REDUCTORA ITALIANA', price: 15.00, originalPrice: null, category: 'Complementos', subcategory: null, tags: ['Complementos', 'Fiesta', 'Casual'], image: 'https://jandulamodautrera.es/wp-content/uploads/2025/03/IMG_2026.jpg', description: 'Media reductora de fabricación italiana. Confort y estilización.', sizes: ['S/M', 'L/XL'] },
];

// Continue with part 2 - will be appended
fs.writeFileSync('/tmp/products_part1.json', JSON.stringify(products, null, 2));
console.log('Part 1 written: ' + products.length + ' products');
